@extends('layouts.public')
@php
    $value = fn ($key, $fallback = '') => isset($settings[$key])
        ? ($settings[$key]->displayValue() ?? $fallback)
        : $fallback;
    $asset = fn ($path) => str_starts_with((string) $path, 'uploads/')
        ? asset('storage/'.$path)
        : asset($path);
    $phones = preg_split('/\R+/', trim($value('phones')));
    $wa = preg_replace('/\D/', '', $value('whatsapp'));
    if (str_starts_with($wa, '0')) $wa = '225'.substr($wa, 1);
@endphp
@section('content')
<header><nav id="navbar" class="navbar navbar-expand-xl navbar-light fixed-top" aria-label="Primary navigation"><div class="container">
 <a class="navbar-brand" href="#home"><img src="{{ $asset($value('logo','images/auto-motors-logo.png')) }}" alt="AUTO MOTORS SARL" width="132" height="82"></a>
 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="{{ __('messages.menu') }}"><span class="navbar-toggler-icon"></span></button>
 <div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav ms-auto align-items-xl-center gap-xl-1">
 @foreach(__('messages.nav') as $id=>$label)<li class="nav-item"><a class="nav-link" href="#{{ $id }}">{{ $label }}</a></li>@endforeach
 </ul><div class="locale-switch ms-xl-3"><a class="{{ app()->isLocale('fr')?'active':'' }}" href="{{ route('locale','fr') }}">FR</a><span>/</span><a class="{{ app()->isLocale('en')?'active':'' }}" href="{{ route('locale','en') }}">EN</a></div>
 <a class="btn btn-brand btn-sm ms-xl-3 mt-3 mt-xl-0" href="https://wa.me/{{ $wa }}" target="_blank" rel="noopener"><i class="bi bi-whatsapp"></i> WhatsApp</a></div>
</div></nav></header>
<main id="main">
<section id="home" class="hero" style="--hero:url('{{ $asset($value('hero_image','images/hero-automotive.png')) }}')"><div class="hero-car-scene" aria-hidden="true"><div class="hero-car"></div></div><div class="hero-glow"></div><div class="container hero-content"><div class="col-lg-7">
 <p class="eyebrow hero-enter">{{ __('messages.hero_kicker') }}</p><h1 class="hero-enter">{{ $value('company_name','AUTO MOTORS SARL') }}</h1><p class="hero-lead hero-enter">{{ $value('hero_title') }}</p><p class="hero-copy hero-enter">{{ $value('hero_subtitle') }}</p>
 <div class="d-flex flex-wrap gap-3 hero-enter"><a class="btn btn-brand btn-lg" href="#products">{{ __('messages.discover') }} <i class="bi bi-arrow-down-right"></i></a><a class="btn btn-outline-light btn-lg" href="#contact">{{ __('messages.contact_us') }}</a></div>
</div></div><div class="road-line" aria-hidden="true"></div></section>

<section id="about" class="section"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6 reveal"><div class="about-visual"><img src="{{ asset('images/hero-automotive.png') }}" alt="{{ app()->isLocale('fr')?'Univers automobile Auto Motors':'Auto Motors automotive environment' }}" loading="lazy"><span class="visual-tag"><i class="bi bi-geo-alt-fill"></i> Côte d’Ivoire</span></div></div><div class="col-lg-6 reveal"><p class="eyebrow">AUTO MOTORS SARL</p><h2>{{ __('messages.about_title') }}</h2><p class="lead-muted">{{ $value('about') }}</p><div class="mission"><i class="bi bi-bullseye"></i><div><small>{{ __('messages.mission') }}</small><strong>{{ $value('mission') }}</strong></div></div><p class="mt-4"><i class="bi bi-truck me-2 text-brand"></i>{{ $value('delivery') }}</p></div></div></div></section>

<section id="services" class="section section-muted"><div class="container"><div class="section-heading reveal"><p class="eyebrow">Services</p><h2>{{ __('messages.services_title') }}</h2><p>{{ __('messages.services_intro') }}</p></div><div class="row g-4">@foreach($services as $service)<div class="col-md-6 col-lg-4 reveal"><article class="service-card h-100">@if($service->image)<img src="{{ $asset($service->image) }}" alt="{{ $service->localized('title') }}" loading="lazy">@endif<div class="service-icon"><i class="bi {{ $service->icon }}"></i></div><span class="card-index">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $service->localized('title') }}</h3><p>{{ $service->localized('description') }}</p></article></div>@endforeach</div></div></section>

<div id="catalogue"><section id="products" class="section"><div class="container"><div class="section-heading reveal"><p class="eyebrow">Catalogue</p><h2>{{ __('messages.products_title') }}</h2><p>{{ __('messages.products_intro') }}</p></div><div class="filter-bar reveal" role="navigation" aria-label="Product categories"><a class="filter-btn {{ request('category')?'':'active' }}" href="{{ route('home') }}#products">{{ __('messages.all') }}</a>@foreach($categories as $category)<a class="filter-btn {{ request('category')===$category->slug?'active':'' }}" href="{{ route('home',['category'=>$category->slug]) }}#products">{{ $category->localized('name') }}</a>@endforeach</div>
<p data-catalogue-error role="alert" hidden>{{ app()->isLocale('fr') ? "Impossible de charger le catalogue. Veuillez réessayer." : "Unable to load the catalogue. Please try again." }}</p><div class="row g-4 product-grid">@forelse($products as $product)<div class="col-sm-6 col-lg-3 product-item reveal" data-category="{{ $product->category->slug }}"><article class="product-card h-100">@if($product->main_image)<img src="{{ $asset($product->main_image) }}" alt="{{ $product->localized('name') }}" loading="lazy">@else<div class="product-placeholder"><i class="bi bi-gear-wide-connected"></i></div>@endif<div class="p-4"><span class="product-category">{{ $product->category->localized('name') }}</span><h3>{{ $product->localized('name') }}</h3><p>{{ $product->localized('description') }}</p>@if($product->image_reference)<small>{{ __('messages.ref') }}: {{ $product->image_reference }}</small>@endif<div class="price">{{ $product->price ? number_format($product->price,0,',',' ').' FCFA' : __('messages.price_on_request') }}</div>@if($product->main_image || $product->images->isNotEmpty())<button class="btn btn-link px-0 mt-2" data-bs-toggle="modal" data-bs-target="#product{{ $product->id }}">{{ __('messages.details') }} <i class="bi bi-arrow-right"></i></button>@endif</div></article></div>@empty<div class="col-12"><div class="empty-state reveal"><i class="bi bi-tools"></i><p>{{ __('messages.no_products') }}</p><a href="#contact" class="btn btn-brand">{{ __('messages.contact_us') }}</a></div></div>@endforelse</div><div class="mt-5 d-flex justify-content-center">{{ $products->links() }}</div></div></section>
@foreach($products as $product)@if($product->main_image || $product->images->isNotEmpty())<div class="modal fade" id="product{{ $product->id }}" tabindex="-1" aria-labelledby="productTitle{{ $product->id }}" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-4" id="productTitle{{ $product->id }}">{{ $product->localized('name') }}</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('messages.close') }}"></button></div><div class="modal-body"><div class="row g-3">@if($product->main_image)<div class="col-md-6"><img class="img-fluid" src="{{ $asset($product->main_image) }}" alt="{{ $product->localized('name') }}"></div>@endif @foreach($product->images as $image)<div class="col-md-6"><img class="img-fluid" src="{{ $asset($image->path) }}" alt="{{ app()->isLocale('fr')?($image->alt_fr?:$product->name_fr):($image->alt_en?:$product->name_en) }}" loading="lazy"></div>@endforeach</div></div></div></div></div>@endif @endforeach

</div><section id="vehicles" class="section vehicle-section"><div class="container"><div class="section-heading text-white reveal"><p class="eyebrow">Fleet fit</p><h2>{{ __('messages.vehicles_title') }}</h2><p>{{ __('messages.vehicles_intro') }}</p></div><div class="row g-4">@foreach($vehicleCategories as $category)<div class="col-lg-6 reveal"><div class="vehicle-group"><h3>{{ $category->localized('name') }}</h3><div class="brand-grid">@foreach($category->vehicles as $vehicle)<article class="brand-tile">@if($vehicle->image)<img src="{{ $asset($vehicle->image) }}" alt="{{ $vehicle->name }}" loading="lazy">@else<span>{{ mb_substr($vehicle->name,0,1) }}</span>@endif<div><strong>{{ $vehicle->name }}</strong>@if($vehicle->localized('description'))<small>{{ $vehicle->localized('description') }}</small>@endif</div></article>@endforeach</div></div></div>@endforeach</div></div></section>

<section class="section why-section"><div class="container"><div class="section-heading reveal"><p class="eyebrow">AUTO MOTORS</p><h2>{{ __('messages.why_title') }}</h2></div><div class="row g-3 justify-content-center">@foreach($advantages as $advantage)<div class="col-6 col-md-4 col-lg reveal"><div class="advantage"><i class="bi {{ $advantage->icon }}"></i><strong>{{ $advantage->localized('title') }}</strong></div></div>@endforeach</div></div></section>

<section id="faq" class="section section-muted"><div class="container"><div class="section-heading reveal"><p class="eyebrow">FAQ</p><h2>{{ __('messages.faq_title') }}</h2></div>@if($faqs->isEmpty())<div class="empty-state reveal"><i class="bi bi-chat-square-dots"></i><p>{{ __('messages.no_faq') }}</p></div>@else<div class="accordion accordion-flush faq-accordion reveal" id="faqAccordion">@foreach($faqs as $faq)<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button {{ $loop->first?'':'collapsed' }}" type="button" data-bs-toggle="collapse" data-bs-target="#faq{{ $faq->id }}" aria-expanded="{{ $loop->first?'true':'false' }}" aria-controls="faq{{ $faq->id }}">{{ $faq->localized('question') }}</button></h3><div id="faq{{ $faq->id }}" class="accordion-collapse collapse {{ $loop->first?'show':'' }}" data-bs-parent="#faqAccordion"><div class="accordion-body">{{ $faq->localized('answer') }}</div></div></div>@endforeach</div>@endif</div></section>

<section id="contact" class="contact-section"><div class="container"><div class="contact-panel reveal"><div class="row g-5"><div class="col-lg-5"><p class="eyebrow">Contact</p><h2>{{ __('messages.contact_title') }}</h2><p>{{ $value('delivery') }}</p><a class="btn btn-light btn-lg" href="https://wa.me/{{ $wa }}" target="_blank" rel="noopener"><i class="bi bi-whatsapp"></i> {{ __('messages.whatsapp') }}</a></div><div class="col-lg-7"><div class="contact-grid"><div><i class="bi bi-geo-alt"></i><small>{{ __('messages.address') }}</small><strong>{{ $value('address') }}</strong></div><div><i class="bi bi-telephone"></i><small>{{ __('messages.phone') }}</small>@foreach($phones as $phone)<a href="tel:{{ preg_replace('/\D/','',$phone) }}">{{ $phone }}</a>@endforeach</div><div><i class="bi bi-envelope"></i><small>{{ __('messages.email') }}</small><a href="mailto:{{ $value('email') }}">{{ $value('email') }}</a></div><div><i class="bi bi-truck"></i><small>{{ __('messages.delivery') }}</small><strong>{{ $value('delivery') }}</strong></div></div></div></div></div></div></section>
</main>
<footer><div class="container"><div class="footer-grid"><img src="{{ $asset($value('logo','images/auto-motors-logo.png')) }}" alt="AUTO MOTORS SARL" width="150" height="93"><nav aria-label="Footer navigation">@foreach(__('messages.nav') as $id=>$label)<a href="#{{ $id }}">{{ $label }}</a>@endforeach</nav><div><a href="mailto:{{ $value('email') }}">{{ $value('email') }}</a><br>{{ $value('address') }}</div></div><div class="footer-bottom">© {{ date('Y') }} AUTO MOTORS SARL. {{ __('messages.rights') }} <a href="{{ route('login') }}">{{ __('messages.admin') }}</a></div></div></footer>
<a id="backTop" class="back-top" href="#home" aria-label="{{ __('messages.back_top') }}"><i class="bi bi-arrow-up"></i></a>
@endsection
